# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phunter < Formula
  desc "Terminal UI for hunting and killing processes listening on TCP ports"
  homepage "https://github.com/derangga/phunter"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/derangga/phunter/releases/download/v0.2.1/phunter_darwin_amd64.tar.gz"
      sha256 "3e79180c92352bbcbe45040aa9105034f98da96e603f52d54eebceee7faafaef"

      define_method(:install) do
        bin.install "phunter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/derangga/phunter/releases/download/v0.2.1/phunter_darwin_arm64.tar.gz"
      sha256 "81f1718dc44dc84c3134b194c07f070252480a178af9972a2b370ac8fadc70e9"

      define_method(:install) do
        bin.install "phunter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/derangga/phunter/releases/download/v0.2.1/phunter_linux_amd64.tar.gz"
      sha256 "55e3d5ffd17cb82ef3d90f2e255a9fe6cf5806805cee248f6ed398d337cbff31"
      define_method(:install) do
        bin.install "phunter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/derangga/phunter/releases/download/v0.2.1/phunter_linux_arm64.tar.gz"
      sha256 "a45292d8b8049b53c39378c35a86a9960b68b0358f165d79aa4463b2abbef72b"
      define_method(:install) do
        bin.install "phunter"
      end
    end
  end
end
