# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phunter < Formula
  desc "Terminal UI for hunting and killing processes listening on TCP ports"
  homepage "https://github.com/derangga/phunter"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/derangga/phunter/releases/download/v0.3.0/phunter_darwin_amd64.tar.gz"
      sha256 "13894839250a8a723cb4673865b80ed94d0258b032652a856c5c2be2e3c52171"

      define_method(:install) do
        bin.install "phunter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/derangga/phunter/releases/download/v0.3.0/phunter_darwin_arm64.tar.gz"
      sha256 "36079dd7b217788def796a27b5fd38e86feaba1de8713e8945ade9e4d1ffb147"

      define_method(:install) do
        bin.install "phunter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/derangga/phunter/releases/download/v0.3.0/phunter_linux_amd64.tar.gz"
      sha256 "a5fabaa115cdabf94972c0188ce6995eca1d99e644b0272f179daa7573e280cb"
      define_method(:install) do
        bin.install "phunter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/derangga/phunter/releases/download/v0.3.0/phunter_linux_arm64.tar.gz"
      sha256 "f6601bc20b56cb23a2410d768814ac200357018a5f87e92f9ee17c029afda994"
      define_method(:install) do
        bin.install "phunter"
      end
    end
  end
end
